package bd.com.ipay.ipayskeleton.Utilities;

public class BusinessRuleConstants {
    public static final String SERVICE_RULE_SEND_MONEY_MIN_AMOUNT_PER_PAYMENT = "SENDMONEY_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_SEND_MONEY_MAX_AMOUNT_PER_PAYMENT = "SENDMONEY_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_SEND_MONEY_VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_SEND_MONEY_PIN_REQUIRED = "PIN_REQUIRED";

    public static final String SERVICE_RULE_REQUEST_MONEY_MIN_AMOUNT_PER_PAYMENT = "REQUESTMONEY_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_REQUEST_MONEY_MAX_AMOUNT_PER_PAYMENT = "REQUESTMONEY_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_REQUEST_MONEY_VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_REQUEST_MONEY_PIN_REQUIRED = "PIN_REQUIRED";


    public static final String SERVICE_RULE_ADD_MONEY_MIN_AMOUNT_PER_PAYMENT = "ADDMONEY_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_ADD_MONEY_MAX_AMOUNT_PER_PAYMENT = "ADDMONEY_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_ADD_MONEY_VERIFICATION_REQUIRED = "ADDMONEY_VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_ADD_MONEY_PIN_REQUIRED = "PIN_REQUIRED";


    public static final String SERVICE_RULE_TOP_UP_MIN_AMOUNT_PER_PAYMENT = "TOPUP_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_TOP_UP_MAX_AMOUNT_PER_PAYMENT = "TOPUP_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_TOP_UP_VERIFICATION_REQUIRED = "TOPUP_VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_TOP_UP_PIN_REQUIRED = "PIN_REQUIRED";

    public static final String SERVICE_RULE_WITHDRAW_MONEY_MIN_AMOUNT_PER_PAYMENT = "WITHDRAW_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_WITHDRAW_MONEY_MAX_AMOUNT_PER_PAYMENT = "WITHDRAW_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_WITHDRAW_MONEY_VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_WITHDRAW_MONEY_PIN_REQUIRED = "PIN_REQUIRED";


    public static final String SERVICE_RULE_MAKE_PAYMENT_MIN_AMOUNT_PER_PAYMENT = "PAYMENT_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_MAKE_PAYMENT_MAX_AMOUNT_PER_PAYMENT = "PAYMENT_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_MAKE_PAYMENT_VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_MAKE_PAYMENT_PIN_REQUIRED = "PIN_REQUIRED";
    public static final String SERVICE_RULE_MAKE_PAYMENT_LOCATION_REQUIRED = "LOCATION_REQUIRED";


    public static final String SERVICE_RULE_REQUEST_PAYMENT_MIN_AMOUNT_PER_PAYMENT = "REQUEST_PAYMENT_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_REQUEST_PAYMENT_MAX_AMOUNT_PER_PAYMENT = "REQUEST_PAYMENT_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_REQUEST_PAYMENT_VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED";
    public static final String SERVICE_RULE_REQUEST_PAYMENT_PIN_REQUIRED = "PIN_REQUIRED";
    public static final String SERVICE_RULE_REQUEST_PAYMENT_LOCATION_REQUIRED = "LOCATION_REQUIRED";


    public static final String SERVICE_RULE_ADD_CARDMONEY_MIN_AMOUNT_SINGLE = "ADD_CARDMONEY_MIN_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_ADD_CARDMONEY_MAX_AMOUNT_SINGLE = "ADD_CARDMONEY_MAX_AMOUNT_SINGLE";
    public static final String SERVICE_RULE_ADD_CARDMONEY_VERIFICATION_REQUIRED = "ADD_CARDMONEY_VERIFICATION_REQUIRED";
}
